# Generated by Django 4.0.5 on 2022-07-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OJ_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='inputdoc',
            new_name='input',
        ),
        migrations.RenameField(
            model_name='testcase',
            old_name='outputdoc',
            new_name='output',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='score',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='answercode',
        ),
        migrations.AddField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='EASY', max_length=6),
        ),
        migrations.AlterField(
            model_name='submission',
            name='verdict',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('COMPILATION_ERROR', 'Compilation Error'), ('Wrong Output', 'Wrong Output'), ('TIME LIMIT EXCEEDED', 'Time Limit Exceeded'), ('RUNTIME ERROR', 'Runtime Error')], max_length=20),
        ),
    ]
